image: mono

stages:
    - build
    - test

before_script:
    - nuget restore -NonInteractive

publish:
    stage: build
    only:
        - master
    artifacts:
        paths:
            - GitLabAPI/bin/Release/GitLabAPI.dll
            - GitLabAPI/bin/Release/GitLabAPI.mdb
            - GitLabAPI/*.nupkg
    script:
        - xbuild "GitLabAPI.sln" /p:Configuration=Release
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.Tests/bin/Release/GitLabAPI.Tests.dll
        - cd GitLabAPI
        - nuget pack GitLabAPI.nuspec
        - nuget setApiKey $NUGET_API_KEY -verbosity quiet
        - nuget push GitLabAPI.*.nupk

test:
    stage: test
    except:
        - master
    script:
        - xbuild "GitLabAPI.sln" /p:Configuration=Debug
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.Tests/bin/Debug/GitLabAPI.Tests.dll
        - cd GitLabAPI
        - nuget pack GitLabAPI.nuspec