image: mono

stages:
    - build
    - test

before_script:
    - nuget restore -NonInteractive

build_master:
    stage: build
    only:
        - master
    artifacts:
        paths:
            - GitLabAPI/bin/Release/*
            - GitLabAPI/*.nupkg
    script:
        - xbuild "GitLabAPI.sln" /p:Configuration=Release
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.Tests/bin/Release/GitLabAPI.Tests.dll
        - cd GitLabAPI
        - nuget pack GitLabAPI.nuspec
        - nuget setApiKey $NUGET_API_KEY -verbosity quiet
        - nuget push GitLabAPI.*.nupkg

test_release:
    stage: test
    only:
        - /^release-.*$/
    artifacts:
        paths:
            - GitLabAPI/bin/Debug/*
            - GitLabAPI/*.nupkg
    script:
        - xbuild "GitLabAPI.sln" /p:Configuration=Debug
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.Tests/bin/Debug/GitLabAPI.Tests.dll
        - cd GitLabAPI
        - nuget pack GitLabAPI.nuspec

test_develop:
    stage: test
    except:
        - master
        - /^release-.*$/
    script:
        - xbuild "GitLabAPI.sln" /p:Configuration=Debug
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.Tests/bin/Debug/GitLabAPI.Tests.dll
        - cd GitLabAPI
        - nuget pack GitLabAPI.nuspec