image: mono

stages:
    - build
    - test
    - deploy

before_script:
    - nuget restore -NonInteractive

.build_template: &build_template
    stage: build
    artifacts:
        paths:
            - GitLabAPI/bin/$CONFIGURATION/*
            - GitLabAPI.Tests/bin/$CONFIGURATION/*
    script:
        - xbuild "GitLabAPI.sln" /p:Configuration=$CONFIGURATION

.test_template: &test_template
    stage: test
    script:
        - packages/xunit.runner.console.2.1.0/tools/xunit.console GitLabAPI.Tests/bin/$CONFIGURATION/GitLabAPI.Tests.dll

build_master:
    variables:
        CONFIGURATION: "Release"
    only:
        - master
    <<: *build_template

test_master:
    variables:
        CONFIGURATION: "Release"
    only:
        - master
    <<: *test_template

build_develop:
    variables:
        CONFIGURATION: "Debug"
    only:
        - develop
        - /^release\/.*$/
        - /^feature\/.*$/
        - /^hotfix\/.*$/
    <<: *build_template

test_develop:
    variables:
        CONFIGURATION: "Debug"
    only:
        - develop
        - /^release\/.*$/
        - /^feature\/.*$/
        - /^hotfix\/.*$/
    <<: *test_template