image: mono

stages:
    - build
    - test

before_script:
    - nuget restore -NonInteractive

publish:
    stage: build
    only:
        - /^release-.*$/
    artifacts:
        paths:
            - GitLab.NET/bin/Release/GitLab.NET.*
            - GitLab.NET.*.nupkg
    script:
        - xbuild "GitLab.NET.sln" /p:Configuration=Release
        - mono packages/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe GitLab.NET.Tests/bin/Release/GitLab.NET.Tests.dll
        - nuget pack GitLab.NET.nuspec
        - nuget setApiKey $NUGET_API_KEY -verbosity quiet
        - nuget push GitLab.NET.*.nupkg

test_release:
    stage: test
    only:
        - production
    script:
        - xbuild "GitLab.NET.sln" /p:Configuration=Release
        - mono packages/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe GitLab.NET.Tests/bin/Release/GitLab.NET.Tests.dll
        - nuget pack GitLab.NET.nuspec

test_debug:
    stage: test
    except:
        - production
        - /^release-.*$/
    script:
        - xbuild "GitLab.NET.sln" /p:Configuration=Debug
        - mono packages/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe GitLab.NET.Tests/bin/Debug/GitLab.NET.Tests.dll
        - nuget pack GitLab.NET.nuspec