image: mono

stages:
    - build
    - test

before_script:
    - nuget restore -NonInteractive

publish:
    stage: build
    only:
        - production
    artifacts:
        paths:
            - GitLabAPI.NET/bin/Release/GitLabAPI.dll
            - GitLabAPI.NET/bin/Release/GitLabAPI.mdb
            - GitLabAPI.NET.*.nupkg
    script:
        - xbuild "GitLabAPI.NET.sln" /p:Configuration=Release
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.NET.Tests/bin/Release/GitLabAPI.NET.Tests.dll
        - nuget pack GitLabAPI.NET.nuspec
        - nuget setApiKey $NUGET_API_KEY -verbosity quiet
        - nuget push GitLabAPI.NET.*.nupk

test:
    stage: test
    except:
        - production
    script:
        - xbuild "GitLabAPI.NET.sln" /p:Configuration=Debug
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLabAPI.NET.Tests/bin/Debug/GitLabAPI.NET.Tests.dll
        - nuget pack GitLabAPI.NET.nuspec