image: mono

stages:
    - build
    - test

before_script:
    - nuget restore -NonInteractive

publish:
    stage: build
    only:
        - production
    artifacts:
        paths:
            - GitLab.NET/bin/Release/GitLab.dll
            - GitLab.NET/bin/Release/GitLab.mdb
            - GitLab.NET.*.nupkg
    script:
        - xbuild "GitLab.NET.sln" /p:Configuration=Release
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLab.NET.Tests/bin/Release/GitLab.NET.Tests.dll
        - nuget pack GitLab.NET.nuspec
        - nuget setApiKey $NUGET_API_KEY -verbosity quiet
        - nuget push GitLabAPI.NET.*.nupk

test:
    stage: test
    except:
        - production
    script:
        - xbuild "GitLab.NET.sln" /p:Configuration=Debug
        - mono packages/xunit.runner.console.2.1.0/tools/xunit.console.exe GitLab.NET.Tests/bin/Debug/GitLab.NET.Tests.dll
        - nuget pack GitLab.NET.nuspec